"""adding tables of categories,upvote,downvote

Revision ID: 4848c5a32802
Revises: da24ba95ca09
Create Date: 2019-02-27 10:28:23.412978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4848c5a32802'
down_revision = 'da24ba95ca09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('pitch_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'pitch', ['pitch_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'])
    op.add_column('pitch', sa.Column('category', sa.String(length=255), nullable=True))
    op.add_column('pitch', sa.Column('downvote', sa.Integer(), nullable=True))
    op.add_column('pitch', sa.Column('upvote', sa.Integer(), nullable=True))
    op.add_column('pitch', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitch', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.drop_column('pitch', 'user_id')
    op.drop_column('pitch', 'upvote')
    op.drop_column('pitch', 'downvote')
    op.drop_column('pitch', 'category')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'pitch_id')
    # ### end Alembic commands ###
