"""Initial Migration

Revision ID: 7f265e7a5ec4
Revises: a66cf42e2dfa
Create Date: 2019-02-28 10:03:06.379452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f265e7a5ec4'
down_revision = 'a66cf42e2dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'title')
    # ### end Alembic commands ###
