"""Initial Migration

Revision ID: a66cf42e2dfa
Revises: 4848c5a32802
Create Date: 2019-02-27 13:33:22.130949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66cf42e2dfa'
down_revision = '4848c5a32802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'downvote')
    op.drop_column('pitch', 'upvote')
    op.drop_column('pitch', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitch', sa.Column('upvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitch', sa.Column('downvote', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
