"""Initial Migration

Revision ID: c04ff50a7844
Revises: 7f265e7a5ec4
Create Date: 2019-02-28 13:31:35.485685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04ff50a7844'
down_revision = '7f265e7a5ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('category', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'category')
    # ### end Alembic commands ###
